# Recap:

NumPy is a Python library that is widely used for numerical computing and data analysis tasks. One of its core features is the manipulation of arrays and matrices. In this guide, we'll explore how to create, manipulate, and perform basic operations on arrays and matrices using NumPy.

### Creating Arrays:

NumPy arrays are homogeneous, multi-dimensional data structures that can store elements of the same data type. Here's how you can create arrays:

In [ ]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# Create a 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)


### Array Attributes:

Arrays have several attributes that provide information about their shape, size, and data type:

In [ ]:
print(arr1d.shape)   # Shape of the array
print(arr2d.ndim)    # Number of dimensions
print(arr2d.dtype)   # Data type of elements

### Accessing Elements:

You can access elements of an array using indexing and slicing:

In [4]:
print(arr1d[0])         # Accessing the first element
print(arr2d[1, 2])      # Accessing an element in a 2D array
print(arr1d[2:4])       # Slicing a 1D array
print(arr2d[:, 1:])     # Slicing rows and columns of a 2D array

1
6
[3 4]
[[2 3]
 [5 6]]


### Array Operations:

NumPy allows you to perform element-wise operations on arrays without using explicit loops:

In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Scalar addition
result = arr + 10
print(result)

# Element-wise multiplication
result = arr * 2
print(result)

# Element-wise square root
result = np.sqrt(arr)
print(result)

[11 12 13 14 15]
[ 2  4  6  8 10]
[1.         1.41421356 1.73205081 2.         2.23606798]
